require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mail_logs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MailLog. As you add validations to MailLog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MailLog.create! valid_attributes
      get mail_logs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mail_log = MailLog.create! valid_attributes
      get mail_log_url(mail_log)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mail_log_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      mail_log = MailLog.create! valid_attributes
      get edit_mail_log_url(mail_log)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MailLog" do
        expect {
          post mail_logs_url, params: { mail_log: valid_attributes }
        }.to change(MailLog, :count).by(1)
      end

      it "redirects to the created mail_log" do
        post mail_logs_url, params: { mail_log: valid_attributes }
        expect(response).to redirect_to(mail_log_url(MailLog.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MailLog" do
        expect {
          post mail_logs_url, params: { mail_log: invalid_attributes }
        }.to change(MailLog, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post mail_logs_url, params: { mail_log: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mail_log" do
        mail_log = MailLog.create! valid_attributes
        patch mail_log_url(mail_log), params: { mail_log: new_attributes }
        mail_log.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mail_log" do
        mail_log = MailLog.create! valid_attributes
        patch mail_log_url(mail_log), params: { mail_log: new_attributes }
        mail_log.reload
        expect(response).to redirect_to(mail_log_url(mail_log))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        mail_log = MailLog.create! valid_attributes
        patch mail_log_url(mail_log), params: { mail_log: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mail_log" do
      mail_log = MailLog.create! valid_attributes
      expect {
        delete mail_log_url(mail_log)
      }.to change(MailLog, :count).by(-1)
    end

    it "redirects to the mail_logs list" do
      mail_log = MailLog.create! valid_attributes
      delete mail_log_url(mail_log)
      expect(response).to redirect_to(mail_logs_url)
    end
  end
end
